moonlight-mod/moonlight

- packages/core-extensions/src/moonbase/ui/config/index.tsx
- packages/core-extensions/src/moonbase/ui/extensions/card.tsx
- packages/core-extensions/src/moonbase/ui/extensions/filterBar.tsx
- packages/core-extensions/src/moonbase/ui/extensions/index.tsx
- packages/core-extensions/src/moonbase/ui/extensions/info.tsx
- packages/core-extensions/src/moonbase/ui/extensions/settings.tsx
- packages/core-extensions/src/moonbase/ui/index.tsx
- packages/core-extensions/src/moonbase/webpackModules/stores.ts
- packages/types/src/coreExtensions/components.ts
- split moonbase into tabs
- add settings for all the other config options
> Moonbase config tab

- .vscode/tasks.json
- packages/core/src/patch.ts
Adds support for `\i`, which translates to [A-Za-z_$][\\w$]*
> Webpack patch identifiers

- packages/core-extensions/src/spacepack/webpackModules/spacepack.ts
- packages/types/src/coreExtensions.ts
Adds spacepack.filterReal, which takes an array of webpack modules and returns modules that id is just numbers.
This is intended so you dont match yourself in a webpack module
> spacepack: filter real function

- packages/core-extensions/src/disableSentry/host.ts
- packages/core-extensions/src/disableSentry/node.ts
- packages/core/src/util/data.ts
- packages/injector/src/index.ts
- packages/node-preload/src/index.ts
- packages/types/src/constants.ts
Rewrite of #23 to keep one injector codebase
> injector: support other patch methods

- packages/core-extensions/src/moonbase/index.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/settings.tsx
- packages/types/src/config.ts
- packages/types/src/coreExtensions/components.ts
This adds the ability for extensions to have a multiline string setting in moonbase, mostly based off of the String setting type but using TextArea so it can be multiline
Looks like this:
> moonbase: Implement multiline text input for settings

- packages/core-extensions/src/moonbase/types.ts
- packages/core-extensions/src/moonbase/webpackModules/stores.ts
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/card.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/index.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/info.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/settings.tsx
moonbase previously used the extension ID to differentiate between extensions. This worked well until two extensions used the same ID on different repositories. To fix this, every extension is assigned an auto-incrementing "unique ID" and is indexed and accessed by that ID. When an extension with the same extension ID but different unique ID is installed, the installation buttons are disabled.
I haven't tested updating an extension yet. I believe two extensions on the same repository will cause problems (as repository URL is used for differentiating sometimes) but I believe that to be considered an invalid repository.
> moonbase: Use unique IDs for extension management

- packages/core-extensions/src/contextMenu/index.tsx
- packages/core-extensions/src/contextMenu/webpackModules/contextMenu.ts
The previously patched function may not exist for some context menu element types, this one is guaranteed to exist.
> contextMenu: Much more robust closing detection

- packages/core/src/extension/loader.ts
- packages/core/src/patch.ts
- packages/core/src/util/event.ts
- packages/types/src/core/event.ts
- packages/types/src/extension.ts
- packages/types/src/globals.ts
- packages/web-preload/package.json
- packages/web-preload/src/index.ts
- pnpm-lock.yaml
Exposes patcher internals to the moonlight global
This can be useful for extensions that take advantage of lazy loading chunks, and can be used to sideload other client mods
This is a request for comments and feedback before I merge
> Expose patcher internals

- packages/core-extensions/src/contextMenu/index.tsx
- packages/core-extensions/src/contextMenu/webpackModules/evilMenu.ts
This reverts the patches from commit b73b2d7ceb97bc9cce88e5395fefa2608635b08f,
whatever warranted that commit has been reverted and is now broken on both
stable and canary.
> core-ext/contextMenu: revert fixed patches

- packages/core-extensions/src/disableSentry/index.ts
- packages/core-extensions/src/quietLoggers/index.ts
- **core-ext/quietLoggers: fix remaining patch**
- **core-ext/disableSentry: patch out call of addBreadcrumbs that bypasses the stub**
> Fix the last of the broken patches

- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/index.tsx
While we switched over to unique IDs for everything extension related in order to circumvent issues with local and remote extensions, the list key was not updated accordingly, resulting in ghost cards.
> Fix moonbase card duplication issue

- packages/core-extensions/src/contextMenu/webpackModules/contextMenu.ts
At some point mixing ESM and CJS exports broke, Cynthia tried to fix this in cddfdb383cb1d20e17083fc21a0757847105c67e before but forgot about the unmangling logic.
> core-ext/contextMenu: fix exports

- packages/types/src/config.ts
- packages/types/src/extension.ts
As said in #155: `pnpx ts-json-schema-generator --path './packages/types/src/*.ts' --type ExtensionManifest -f ./tsconfig.json > ../moonlight-mod.github.io/public/manifest.schema.json`
> Add doc comments for the extension manifest

- packages/core-extensions/src/moonbase/webpackModules/stores.ts
so extensions that just updated stay pinned at the top of the extensions list
> moonbase: don't set `hasUpdate` to false after installing an extension

- packages/core-extensions/src/quietLoggers/index.ts
- packages/core-extensions/src/quietLoggers/manifest.json
> Silence bracket-style logs and highlight.js logs

- packages/injector/src/index.ts
`prefetch-src` is deprecated and causes errors to be thrown in the console when it's present (at least on desktop macOS).
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src
> Remove `prefetch-src` from CSP patching

- packages/core-extensions/src/moonbase/webpackModules/stores.ts
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/card.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/index.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/index.tsx
- packages/core-extensions/src/moonbase/webpackModules/updates.tsx
This revamps Moonbase update handling a bit, dismissing the update notice now gets
rid of extensions that have updates, it is shown by default and extensions stay
after updating all of them.
Additionally, tab bar functionality is fixed after #173.
> moonbase: various fixes

- packages/core-extensions/src/moonbase/webpackModules/stores.ts
You can easily reproduce this by resetting the config file and enabling and disabling Add to global scope in Spacepack. The notice should disappear, but it doesn't.
Initially I was trying to fix #180 but it turns out that was already fixed and I was on the wrong branch :trollface: (I swear I read the docs I just kind of forgot)
> moonbase: Fix restart advice getting stuck when changing option for the first time

- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/card.tsx
The description tab was accidentally deleted in merge commit b7e5982a47db4db63443ac4b74c8f7b737d17cdd.
> moonbase: add back description tab

- packages/core-extensions/src/moonbase/webpackModules/stores.ts
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/card.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/filterBar.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/index.tsx
Closes https://github.com/moonlight-mod/moonlight/issues/184, https://github.com/moonlight-mod/moonlight/issues/182.
- Repositories are diffed upon writing the config, and if so it'll re-fetch the updates (same action as clicking refresh in Moonbase). This only fetches new extensions (won't remove existing ones if you remove a repo), but good enough. (Also, it technically checks for an unneeded update to moonlight, but ehhh who cares)
- Deprecated extensions have a filter next to incompatible, defaulting to off. There's also a new warning badge now. Deprecated extensions that are installed (enabled or disabled) will bypass the filter. This will only hide extensions that are from a remote repository and haven't been installed yet - users will no longer see the extension when they uninstall …
> Misc Moonbase stuff

- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/settings.tsx
This is done for other components... although some it doesn't seem to be possible due to the types (I know it is possible for select components to be disabled though?)
> Disable setting text fields on uninstalled extensions

- packages/core-extensions/src/moonbase/webpackModules/stores.ts
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/card.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/index.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/extensions/info.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/update.tsx
Partially fixes #183 to the extent that I'm comfortable closing it for now.
Also fixes #189.
> More Moonbase things

- packages/core-extensions/src/nativeFixes/host.ts
- packages/core-extensions/src/nativeFixes/manifest.json
To the Discord employee who saw me downloading the .tar.gz about 300 times in the log today: No you didn't.
For some reason it likes to crash when restarting, I don't really know why:
```
2025-01-20T19:53:12.344Z [Modules] Relaunching to install host updates...
blackbox: 2025-01-20T19:53:12.355Z 5 before-quit
[404918:0120/145312.735084:ERROR:command_buffer_proxy_impl.cc(325)] GPU state invalid after WaitForGetOffsetInRange.
[404918:0120/145312.737050:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=139
Segmentation fault (core dumped)
```
...but it does work, testing on an old Canary install I had.
> nativeFixes: Linux updater

- packages/core-extensions/src/moonbase/webpackModules/crashScreen.tsx
- packages/core-extensions/src/spacepack/webpackModules/spacepack.ts
- packages/core/src/patch.ts
The problem: DevTools Sources tab is incredibly laggy
The cause: Using "Patch all" creates hundreds of thousands of modules in one directory which is a lot to render in the sidebar and the list isn't virtualized
The solution: Group patched webpack modules by the first 3 chars of the ID, reducing the amount of rendered files in the sidebar
~~Also my moonbase disappeared but I reverted my changes and it's still gone so maybe unrelated? I need to test if the crash screen works properly but I can't install Crash Me right now.~~ it was my fault
> Fix very laggy Sources tab in DevTools when using "Patch all" in Spacepack

- packages/core-extensions/src/nativeFixes/host.ts
- packages/core-extensions/src/nativeFixes/manifest.json
These options are necessary for hardware accelerated (or possibly in general?) H.265 playback on Linux. The `vaapiIgnoreDriverChecks` option requires `vaapi` to be enabled as well, but there's currently no way to force specific options.
> nativeFixes: Add Vulkan and VAAPI driver check ignore options

- flake.lock
- flake.nix
- nix/default.nix
- nix/overlay.nix
pain, furthermore suffering
- this uses the new approach from nixpkgs
- note that `MOONLIGHT_BRANCH` isn't set, I have no idea if there's a sensible thing to set it to here (unless you want to change the nix packaging for each stable/not-stable release)
- also, the hash for the `fetchDeps` FOD will need updating whenever the dependencies change I guess? (and needs filling in to start with...)
the problem: nixos-24.11 has pnpm_10 built with nodejs_20, afaict. this breaks everything:
```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/x49iyngv15bw7qikpx75qwnjmqfqsh1y-2a1i741ln5mc1gv85nxkybyn8a6dx943-source
source root is 2a1i741ln5mc1gv85nxkybyn8a6dx943-source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": …
```
> WIP: Update Nix flake for pnpm 10

- packages/core-extensions/src/common/index.ts
- packages/core-extensions/src/common/manifest.json
- packages/core-extensions/src/common/webpackModules/icons.ts
- packages/core-extensions/src/moonbase/index.tsx
- packages/core-extensions/src/moonbase/webpackModules/ThemeDarkIcon.tsx
- packages/core-extensions/src/moonbase/webpackModules/ui/update.tsx
- packages/core-extensions/src/moonbase/webpackModules/updates.tsx
- packages/core-extensions/src/moonbase/wp.d.ts
- packages/types/src/coreExtensions/common.ts
- packages/types/src/discord/require.ts
- packages/types/src/import.d.ts
Adds a new library that reimplements icon props parsing, and vendors ThemeDarkIcon into Moonbase. TODO remove the mapping itself so it stops the warning.
> Vendored icons

- .github/workflows/nix.yml
this basically works. an example of how it looks: https://github.com/sersorrel/moonlight/actions/runs/14475141013/job/40598855793
it would be nice to surface the error somewhere a bit more obvious, i don't really have enough experience with GHA to know what kinds of things are possible
shout if you have super negative opinions about the determinate nix installer or want me to point it to lix or something
> Add GHA workflow to ensure Nix flake builds

- packages/core-extensions/src/moonbase/webpackModules/crashScreen.tsx
- packages/core-extensions/src/moonbase/webpackModules/settings.tsx
- packages/core-extensions/src/moonbase/webpackModules/stores.ts
Some minor things I noticed when working on the CSS extension rewrite:
- Moonbase writes new extensions as `{"enabled": true}`, which just looks bad when editing the JSON by hand, even if it's functionally the same. Now, it writes the shorthand (`true`). Other parts of Moonbase will convert the object when required, like it always has.
- Extensions that call `MoonlightNode#writeConfig` don't have their changes show up in Moonbase (since we aren't copying the new config). To solve this, I just split off the actual config processing logic into a new function, and listen to the event to update the store's state. `MoonbaseSettingsStore#writeConfig` will cause the event to fire, which means it works the same as the original code, just with a more indirect path (and AFAIK it'll fire sync so …
> Moonbase config fixes

- nix/default.nix
- packages/browser/manifestv2.json
This allows installing moonlight into Firefox via home-manager. Note that as the addon will be unsigned, the `xpinstall.signatures.required` pref (which is itself not available on stable or beta channels) must be set to `false`.
> Add firefox output to Nix package

- packages/core/src/styles.ts
- packages/web-preload/src/index.ts
The popout and new overlay create separate windows with `window.open` from web, where our styles aren't loaded, breaking some extensions that modify chat. I originally thought I had to mess around with the `setWindowOpenHandler` function in Electron, but it turns out monkeypatching `window.open` gets us a reference to the window, which is both patchless and less complicated.
Tested with Mention Avatars in the overlay and Pronouns in the popout.
> Apply styles to popout and overlay

- packages/browser/src/background-mv2.js
- packages/browser/src/background.js
- packages/core/src/patch.ts
- packages/injector/src/index.ts
- packages/node-preload/src/index.ts
Uses a regex to block entry scripts so the scriptUrls array doesn't have to be changed all the time.
Since every entry script redefines Webpack internals when it loads, it shouldn't cause issues with all of them that aren't `web` being blocked.
> Better script blocking

- packages/core-extensions/src/nativeFixes/host.ts
- packages/core-extensions/src/nativeFixes/manifest.json
Ran into a "fun" issue where Discord set its own `disable-features` in app_bootstrap that overwrote ours, so I had to add a monkeypatch for the Electron function.
> nativeFixes: Add disableFontations

- flake.nix
- nix/default.nix
- nix/home-manager.nix
- nix/overlay.nix
There should be no breaking changes here, only refactoring and deprecating behavior
Now using the withMoonlight feature of the nixpkgs Discord derivation to patch with moonlight
The Discord packages used a nixpkgs instance with `config.allowUnfree` pre-enabled as a workaround for Discord's unfree license
There isn't much reason to provide overridden Discord packages, so these have been deprecated
These packages still function, but will throw an evaluation warning:
```
evaluation warning: The moonlight package 'discord' is deprecated and will be removed in a future release.
Please use 'discord.override {withMoonlight = true;}' instead.
For instructions see: https://moonlight-mod.github.io/using/install/#nixpkgs
```
The new method for users to get the latest version of moonlight is to use …
> Refactor flake

- flake.nix
- nix/overlay.nix
something I didn't notice when looking at #258: `builtins.warn` is [unavailable](https://git.lix.systems/lix-project/lix/issues/579) in Lix, so moonlight currently doesn't work with that implementation:
```
error:
… while evaluating an expression to select 'drvPath' on it
at «internal»:1:552:
… while evaluating strict
at «internal»:1:552:
(stack trace truncated; use '--show-trace' to show the full trace)
error: attribute 'warn' missing
at /nix/store/m8dw9wmjhzyqj8gk3cfm408cvymmgnl1-source/flake.nix:58:35:
57|       # Deprecated overlay
58|       overlays.default = builtins.warn "The moonlight overlay is deprecated and will be removed in a future release." overlay;
|                                   ^
59|     };
```
`lib.warn` behaves similarly and works everywhere.
> nix: Use lib.warn rather than builtins.warn

- packages/core-extensions/src/componentEditor/index.ts
- packages/core-extensions/src/componentEditor/webpackModules/chatButtonList.tsx
- packages/types/src/coreExtensions/componentEditor.ts
- packages/types/src/discord/require.ts
- packages/types/src/import.d.ts
Prettier complains about [this line](https://github.com/Enovale/moonlight/blob/7bf85da6e60be528f2ba149a9c57d83a7edb0294/packages/types/src/coreExtensions/componentEditor.ts#L5) because its not as long as the later lines, but I thought for consistency's sake it should not be shortened.
> Add chat buttons to componentEditor

- .github/workflows/release.yml
Adds manifest v2 and v3 builds, as well as a standalone `browser.js`, to the list of files released:
Closes #273
> Publish browser-related builds in Github releases
