packages/core-extensions/src/moonbase/manifest.json, packages/core-extensions/src/moonbase/ui/config/index.tsx, packages/core-extensions/src/moonbase/ui/extensions/filterBar.tsx, packages/core-extensions/src/moonbase/ui/extensions/index.tsx, packages/core/src/config.ts, packages/types/src/config.ts
- Make saved extension filter a setting
- Remove old save filter switch
=> Moonbase setting improvements improvements

packages/injector/src/index.ts
Requested by voiidiot
Also includes some other misc fixes/changes, more "documentation" comments and rewording of some comments.
=> OpenAsar fixes

packages/core-extensions/src/experiments/index.ts
- old experiments patches v2
- experiments: fix help context menu
=> experiments: fix help context menu

packages/core-extensions/src/disableSentry/index.ts, packages/core-extensions/src/quietLoggers/index.ts
i will kill if discord revert this again
=> some canary fixes

packages/core-extensions/src/moonbase/webpackModules/ui/extensions/filterBar.tsx
=> moonbase: fix filter bar tag item search

packages/core-extensions/src/contextMenu/index.tsx, packages/core-extensions/src/contextMenu/manifest.json, packages/core-extensions/src/contextMenu/webpackModules/contextMenu.ts, packages/core-extensions/src/contextMenu/webpackModules/evilMenu.ts, packages/types/src/coreExtensions.ts, packages/types/src/coreExtensions/contextMenu.ts, packages/types/src/discord/require.ts, packages/types/src/import.d.ts
This is somewhat old and not done yet but I needed to push my changes so I might as well create the PR too.
=> Context menu library

packages/core-extensions/src/noHideToken/index.ts, packages/core-extensions/src/quietLoggers/index.ts, packages/core/src/patch.ts
- **core/patch: Fix some patches being skipped over**
- **noHideToken: Fix patch find**
- **quietLoggers: Update some patches and add voice engine logging hook removal**
=> Fix a bunch of things

packages/core-extensions/src/moonbase/webpackModules/ui/extensions/card.tsx
=> Add implicitly enabled indicator

packages/core-extensions/package.json, packages/core-extensions/src/rocketship/host.ts, packages/core-extensions/src/rocketship/index.ts, packages/core-extensions/src/rocketship/manifest.json, packages/injector/src/index.ts, pnpm-lock.yaml
Surprise! A new Discord distribution for Linux!
This extension is designed to be used with https://github.com/moonlight-mod/rocketship. It won't do anything otherwise. We will need to write checks for Linux.
Closes #64.
=> rocketship

packages/core-extensions/src/moonbase/index.tsx, packages/core-extensions/src/moonbase/style.css, packages/core-extensions/src/moonbase/types.ts, packages/core-extensions/src/moonbase/webpackModules/crashScreen.tsx, packages/core-extensions/src/moonbase/webpackModules/ui/update.tsx
~~TODO: Extension updater, maybe as tabs between crash info and extension updates if any available?~~
=> moonbase: Crash screen hijack with updater

packages/browser/modifyResponseHeaders.json
Seems to fix fetching from remote repositories and such.
=> fix csp in mv3 browser extension

packages/core/src/extension.ts
=> core: prioritise loading developer extensions

packages/core-extensions/src/moonbase/webpackModules/crashScreen.tsx, packages/core/src/patch.ts, packages/types/src/globals.ts, packages/web-preload/src/index.ts
=> moonbase: show possible causes on crash screen

packages/core-extensions/src/moonbase/manifest.json, packages/core-extensions/src/moonbase/webpackModules/settings.tsx
=> moonbase: Move to the top by default

packages/core-extensions/src/moonbase/style.css, packages/core-extensions/src/moonbase/webpackModules/ui/extensions/card.tsx, packages/types/src/extension.ts
Also adds a new `donate` manifest key
=> moonbase: Move links to tab bar, add icon to disambiguate repo source

packages/core-extensions/src/moonbase/webpackModules/ui/update.tsx
=> moonbase: "View changelog" button on stable updates

packages/core-extensions/src/moonbase/style.css, packages/core-extensions/src/moonbase/webpackModules/stores.ts, packages/core-extensions/src/moonbase/webpackModules/ui/extensions/index.tsx
=> moonbase: Update all extensions button

package.json
See https://github.com/moonlight-mod/moonlight/issues/187
=> Revert "add packageManager entry to package.json"

packages/types/src/coreExtensions/commands.ts
=> commands: fix LegacyCommand type

packages/core-extensions/src/moonbase/webpackModules/ui/extensions/settings.tsx
=> moonbase: Number input improvements

packages/core-extensions/src/commands/webpackModules/commands.ts, packages/types/src/coreExtensions/commands.ts
None of this is tested lol yolo
=> More command types

packages/browser/src/index.ts, packages/core/src/extension/loader.ts, packages/core/src/patch.ts, packages/node-preload/src/index.ts, packages/types/src/core/event.ts, packages/types/src/globals.ts, packages/web-preload/src/index.ts
brb it's components fixing time
=> Add events to node-preload

packages/core-extensions/src/moonbase/webpackModules/ui/extensions/filterBar.tsx
She doesn't need to wobble!
https://github.com/user-attachments/assets/69d417de-ae67-4ddd-82ba-b8a60b8dd5aa
=> Move speen class to "refresh updates" icon, rather than entire button, in moonbase panel header

nix/default.nix
this needs updating on every mappings change, huh
this sucks, i'll think about ways to make it not suck
=> Fix pnpmDeps hash

packages/browser/src/background-mv2.js, packages/browser/src/background.js, packages/injector/src/index.ts
We accidentally broke the popout. 🎉
I switched nascar to no longer store the blocked URLs, since we're only loading one script (`web.`) anyways. This assumption may not hold in the future, but it works for now:tm:. I'm keeping the API as expecting an array in case we ever need to apply multiple scripts at once in the future. The checks for `web.` in the script reapplication logic and patcher is still there, just because I don't want to make people full restart for this.
=> Update nascar to fix popout

flake.nix
nixfmt no longer works on directories, so i'm changing this to use the treefmt wrapper
=> use nixfmt-tree
